export const cooldownAbilities: Record<string, ("Q" | "W" | "E" | "R" | "")[]> = {
  Aatrox: ["R", "", ""],
  Ahri: ["E", "R", ""],
  Akali: ["W", "E", "R"],
  Akshan: ["E", "", ""],
  Alistar: ["R", "", ""],
  Ambessa: ["W", "R", ""],
  Amumu: ["R", "", ""],
  Anivia: ["Q", "W", ""],
  Annie: ["R", "", ""],
  Aphelios: ["", "", ""],
  Ashe: ["", "R", ""],
  AurelionSol: ["E", "R", ""],
  Aurora: ["Q", "R", ""],
  Azir: ["E", "R", ""],

  Bard: ["E", "R", ""],
  BelVeth: ["E", "", ""],
  Blitzcrank: ["Q", "", ""],
  Brand: ["Q", "", ""],
  Braum: ["E", "", ""],
  Briar: ["", "", ""],

  Caitlyn: ["E", "", ""],
  Camille: ["E", "R", ""],
  Cassiopeia: ["R", "W", ""],
  ChoGath: ["Q", "R", ""],
  Corki: ["W", "", ""],

  Darius: ["E", "", ""],
  Diana: ["R", "", ""],
  DrMundo: ["R", "", ""],
  Draven: ["", "", ""],

  Ekko: ["E", "R", ""],
  Elise: ["", "", ""],
  Evelynn: ["R", "", ""],
  Ezreal: ["", "", ""],

  Fiddlesticks: ["R", "", ""],
  Fiora: ["W", "R", ""],
  Fizz: ["", "R", ""],

  Galio: ["W", "R", ""],
  Gangplank: ["W", "R", ""],
  Garen: ["R", "W", ""],
  Gnar: ["E", "", ""],
  Gragas: ["", "", ""],
  Graves: ["", "", ""],
  Gwen: ["R", "", ""],

  Hecarim: ["E", "", ""],
  Heimerdinger: ["E", "", ""],
  Hwei: ["E", "", ""],
  Illaoi: ["R", "E", ""],
  Irelia: ["E", "R", ""],
  Ivern: ["Q", "", ""],

  Janna: ["R", "Q", ""],
  JarvanIV: ["R", "", ""],
  Jax: ["E", "", ""],
  Jayce: ["", "", ""],
  Jhin: ["", "", ""],
  Jinx: ["E", "", ""],

  KSante: ["", "", ""],
  Kaisa: ["R", "", ""],
  Kalista: ["", "", ""],
  Karma: ["E", "", ""],
  Karthus: ["R", "", ""],
  Kassadin: ["Q", "R", ""],
  Katarina: ["", "", ""],
  Kayle: ["R", "E", ""],
  Kayn: ["R", "", ""],
  Kennen: ["R", "", ""],
  Khazix: ["R", "E", ""],
  Kindred: ["R", "", ""],
  Kled: ["R", "", ""],
  KogMaw: ["W", "", ""],

  Leblanc: ["W", "E", ""],
  LeeSin: ["", "", ""],
  Leona: ["R", "", ""],
  Lillia: ["R", "", ""],
  Lissandra: ["E", "R", "Q"],
  Lucian: ["", "", ""],
  Lulu: ["R", "W", ""],
  Lux: ["Q", "", ""],

  Malphite: ["R", "E", ""],
  Malzahar: ["R", "", ""],
  Maokai: ["", "", ""],
  MasterYi: ["R", "", ""],
  Mel: ["W", "", ""],
  Milio: ["W", "Q", "R"],
  MissFortune: ["R", "", ""],
  Mordekaiser: ["R", "", ""],
  Morgana: ["Q", "E", ""],

  Naafiri: ["W", "R", ""],
  Nami: ["", "", ""],
  Nasus: ["W", "R", ""],
  Nautilus: ["", "", ""],
  Neeko: ["R", "E", ""],
  Nidalee: ["", "", ""],
  Nilah: ["W", "E", ""],
  Nocturne: ["R", "", ""],
  Nunu: ["W", "", ""],

  Olaf: ["R", "", ""],
  Orianna: ["R", "", ""],
  Ornn: ["R", "", ""],

  Pantheon: ["R", "", ""],
  Poppy: ["W", "", ""],
  Pyke: ["E", "Q", ""],

  Qiyana: ["R", "", ""],
  Quinn: ["E", "", ""],

  Rakan: ["W", "E", ""],
  Rammus: ["", "", ""],
  RekSai: ["", "", ""],
  Rell: ["", "", ""],
  Renata: ["W", "Q", ""],
  Renekton: ["R", "E", ""],
  Rengar: ["R", "", ""],
  Riven: ["E", "R", ""],
  Rumble: ["R", "W", ""],
  Ryze: ["W", "", ""],
  Samira: ["W", "E", ""],
  Sejuani: ["Q", "R", ""],
  Senna: ["W", "", ""],
  Seraphine: ["R", "", ""],
  Sett: ["W", "", ""],
  Shaco: ["Q", "", ""],
  Shen: ["E", "W", "R"],
  Shyvana: ["", "", ""],
  Singed: ["", "", ""],
  Sion: ["W", "", ""],
  Sivir: ["E", "", ""],
  Skarner: ["R", "", ""],
  Smolder: ["E", "", ""],
  Sona: ["", "", ""],
  Soraka: ["R", "", ""],
  Swain: ["E", "R", ""],
  Sylas: ["E", "", ""],
  Syndra: ["E", "R", ""],

  TahmKench: ["R", "", ""],
  Taliyah: ["E", "", ""],
  Talon: ["", "", ""],
  Taric: ["R", "", ""],
  Teemo: ["Q", "", ""],
  Thresh: ["W", "", ""],
  Tristana: ["E", "Q", "W"],
  Trundle: ["R", "", ""],
  Tryndamere: ["R", "", ""],
  TwistedFate: ["R", "W", ""],
  Twitch: ["", "", ""],

  Udyr: ["", "", ""],
  Urgot: ["E", "R", ""],

  Varus: ["R", "", ""],
  Vayne: ["R", "E", ""],
  Veigar: ["E", "", ""],
  Velkoz: ["E", "R", ""],
  Vex: ["", "", ""],
  Vi: ["R", "", ""],
  Viego: ["", "", ""],
  Viktor: ["", "W", "E"],
  Vladimir: ["W", "R", ""],
  Volibear: ["R", "", ""],

  Warwick: ["E", "R", ""],
  Wukong: ["W", "R", ""],

  Xayah: ["R", "W", ""],
  Xerath: ["E", "", ""],
  XinZhao: ["", "", ""],

  Yasuo: ["W", "R", ""],
  Yone: ["E", "R", "W"],
  Yorick: ["W", "R", ""],
  Yuumi: ["", "", ""],
  Yunara: ["W", "R", ""],

  Zac: ["E", "R", ""],
  Zaahen: ["E", "W", "R"],
  Zed: ["W", "R", ""],
  Zeri: ["R", "", ""],
  Ziggs: ["W", "", ""],
  Zilean: ["R", "", ""],
  Zoe: ["E", "", ""],
  Zyra: ["E", "", ""],
};
