ignoredBuiltDependencies:
  - '@prisma/client'

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@tsparticles/engine'
  - esbuild
  - prisma
  - react-tsparticles
  - sharp
  - tsparticles-engine
  - unrs-resolver
