/**
 * Champion origin/region (e.g. Garen = Demacia, Swain = Noxus).
 * Data Dragon does not expose region; this map is curated from League lore/wiki.
 * Key = Data Dragon champion id (e.g. "Garen", "Swain", "DrMundo").
 */

export const CHAMPION_REGION: Record<string, string> = {
  Aatrox: "Shurima",
  Ahri: "Ionia",
  Akali: "Ionia",
  Akshan: "Shurima",
  Alistar: "Runeterra",
  Amumu: "Shurima",
  Anivia: "Freljord",
  Annie: "Noxus",
  Aphelios: "Targon",
  Ashe: "Freljord",
  AurelionSol: "Runeterra",
  Azir: "Shurima",
  Bard: "Runeterra",
  Belveth: "Void",
  Blitzcrank: "Zaun",
  Brand: "Runeterra",
  Braum: "Freljord",
  Briar: "Noxus",
  Caitlyn: "Piltover",
  Camille: "Piltover",
  Cassiopeia: "Noxus",
  Chogath: "Void",
  Corki: "Bandle City",
  Darius: "Noxus",
  Diana: "Targon",
  Draven: "Noxus",
  DrMundo: "Zaun",
  Ekko: "Zaun",
  Elise: "Shadow Isles",
  Evelynn: "Runeterra",
  Ezreal: "Piltover",
  Fiddlesticks: "Runeterra",
  Fiora: "Demacia",
  Fizz: "Bilgewater",
  Galio: "Demacia",
  Gangplank: "Bilgewater",
  Garen: "Demacia",
  Gnar: "Freljord",
  Gragas: "Freljord",
  Graves: "Bilgewater",
  Gwen: "Shadow Isles",
  Hecarim: "Shadow Isles",
  Heimerdinger: "Piltover",
  Hwei: "Ionia",
  Illaoi: "Bilgewater",
  Irelia: "Ionia",
  Ivern: "Ionia",
  Janna: "Zaun",
  JarvanIV: "Demacia",
  Jax: "Runeterra",
  Jayce: "Piltover",
  Jhin: "Ionia",
  Jinx: "Zaun",
  Kaisa: "Void",
  Kalista: "Shadow Isles",
  Karma: "Ionia",
  Karthus: "Shadow Isles",
  Kassadin: "Void",
  Katarina: "Noxus",
  Kayle: "Demacia",
  Kayn: "Ionia",
  Kennen: "Ionia",
  Khazix: "Void",
  Kindred: "Runeterra",
  Kled: "Noxus",
  KogMaw: "Void",
  KSante: "Shurima",
  LeBlanc: "Noxus",
  LeeSin: "Ionia",
  Leona: "Targon",
  Lillia: "Ionia",
  Lissandra: "Freljord",
  Lucian: "Demacia",
  Lulu: "Bandle City",
  Lux: "Demacia",
  Malphite: "Ixtal",
  Malzahar: "Void",
  Maokai: "Shadow Isles",
  MasterYi: "Ionia",
  Milio: "Ixtal",
  MissFortune: "Bilgewater",
  MonkeyKing: "Ionia",
  Mordekaiser: "Noxus",
  Morgana: "Demacia",
  Naafiri: "Shurima",
  Nami: "Targon",
  Nasus: "Shurima",
  Nautilus: "Bilgewater",
  Neeko: "Ixtal",
  Nidalee: "Ixtal",
  Nilah: "Bilgewater",
  Nocturne: "Runeterra",
  Nunu: "Freljord",
  Olaf: "Freljord",
  Orianna: "Piltover",
  Ornn: "Freljord",
  Pantheon: "Targon",
  Poppy: "Demacia",
  Pyke: "Bilgewater",
  Qiyana: "Ixtal",
  Quinn: "Demacia",
  Rakan: "Ionia",
  Rammus: "Shurima",
  RekSai: "Void",
  Rell: "Noxus",
  Renata: "Zaun",
  Renekton: "Shurima",
  Rengar: "Ixtal",
  Riven: "Noxus",
  Rumble: "Bandle City",
  Ryze: "Runeterra",
  Samira: "Noxus",
  Sejuani: "Freljord",
  Senna: "Shadow Isles",
  Seraphine: "Piltover",
  Sett: "Ionia",
  Shaco: "Runeterra",
  Shen: "Ionia",
  Shyvana: "Demacia",
  Singed: "Zaun",
  Sion: "Noxus",
  Sivir: "Shurima",
  Skarner: "Ixtal",
  Smolder: "Runeterra",
  Sona: "Demacia",
  Soraka: "Targon",
  Swain: "Noxus",
  Sylas: "Demacia",
  Syndra: "Ionia",
  TahmKench: "Bilgewater",
  Taliyah: "Shurima",
  Talon: "Noxus",
  Taric: "Targon",
  Teemo: "Bandle City",
  Thresh: "Shadow Isles",
  Tristana: "Bandle City",
  Trundle: "Freljord",
  Tryndamere: "Freljord",
  TwistedFate: "Bilgewater",
  Twitch: "Zaun",
  Udyr: "Freljord",
  Urgot: "Noxus",
  Varus: "Ionia",
  Vayne: "Demacia",
  Veigar: "Bandle City",
  Velkoz: "Void",
  Vex: "Bandle City",
  Vi: "Piltover",
  Viego: "Shadow Isles",
  Viktor: "Zaun",
  Vladimir: "Noxus",
  Volibear: "Freljord",
  Warwick: "Zaun",
  Xayah: "Ionia",
  Xerath: "Shurima",
  XinZhao: "Demacia",
  Yasuo: "Ionia",
  Yone: "Ionia",
  Yuumi: "Bandle City",
  Zac: "Zaun",
  Zaahen: "Shurima",
  Zed: "Ionia",
  Zeri: "Zaun",
  Ziggs: "Zaun",
  Zilean: "Shurima",
  Zoe: "Targon",
  Zyra: "Ixtal",
};

/**
 * Returns the origin region for a champion (Data Dragon id), e.g. "Demacia", "Noxus".
 * Returns undefined if not in the map.
 */
export function getChampionRegion(championId: string): string | undefined {
  if (!championId) return undefined;
  return CHAMPION_REGION[championId];
}
