import type { GuideJungleTierMatchupSectionConfig } from "@/lib/guides/matchupGuideTypes";

export const VIEGO_JUNGLE_TIER_MATCHUPS: GuideJungleTierMatchupSectionConfig = {
  title: "All matchups",
  tiers: [
    {
      id: "nightmare",
      label: "Nightmare",
      subtitle: "P-please don't hurt me >.<",
      tone: "nightmare",
      matchups: [
        { champion: "Lee Sin", possessionValue: 9 },
        { champion: "Talon", possessionValue: 5 },
        { champion: "Kha'Zix", possessionValue: 8 },
        { champion: "Rengar", possessionValue: 6 },
        { champion: "Qiyana", possessionValue: 6 },
      ],
    },
    {
      id: "difficult",
      label: "Difficult",
      subtitle: "It's winnable!!",
      tone: "difficult",
      matchups: [
        { champion: "Kindred", possessionValue: 4 },
        { champion: "Graves", possessionValue: 5 },
        { champion: "Jax", possessionValue: 7 },
        { champion: "Nasus", possessionValue: 5 },
        { champion: "Rammus", possessionValue: 8 },
        { champion: "Evelynn", possessionValue: 4 },
        { champion: "Nocturne", possessionValue: 4 },
        { champion: "Shaco", possessionValue: 5 },
        { champion: "Hecarim", possessionValue: 3 },
      ],
    },
    {
      id: "even",
      label: "Even",
      subtitle: "May the better kitten prevail!",
      tone: "even",
      matchups: [
        { champion: "Amumu", possessionValue: 5 },
        { champion: "Ambessa", possessionValue: 5 },
        { champion: "Bel'Veth", possessionValue: 7 },
        { champion: "Elise", possessionValue: 4 },
        { champion: "Fiddlesticks", possessionValue: 5 },
        { champion: "Gwen", possessionValue: 4 },
        { champion: "Karthus", possessionValue: 5 },
        { champion: "Kayn", possessionValue: 5 },
        { champion: "Maokai", possessionValue: 5 },
        { champion: "Poppy", possessionValue: 6 },
        { champion: "Shyvana", possessionValue: 6 },
        { champion: "Wukong", possessionValue: 6 },
        { champion: "Xin Zhao", possessionValue: 7 },
        { champion: "Zed", possessionValue: 3 },
      ],
    },
    {
      id: "favorable",
      label: "Favored",
      subtitle: "Easy :3",
      tone: "favorable",
      matchups: [
        { champion: "Briar", possessionValue: 4 },
        { champion: "Dr. Mundo", possessionValue: 5 },
        { champion: "Gragas", possessionValue: 5 },
        { champion: "Lillia", possessionValue: 5 },
        { champion: "Naafiri", possessionValue: 6 },
        { champion: "Nidalee", possessionValue: 3 },
        { champion: "Olaf", possessionValue: 6 },
        { champion: "Rek'Sai", possessionValue: 6 },
        { champion: "Sejuani", possessionValue: 6 },
        { champion: "Skarner", possessionValue: 6 },
        { champion: "Udyr", possessionValue: 6 },
        { champion: "Volibear", possessionValue: 5 },
        { champion: "Warwick", possessionValue: 6 },
        { champion: "Zac", possessionValue: 6 },
      ],
    },
    {
      id: "free",
      label: "Free food",
      subtitle: "Awwwwwwwwwwh I'm gonna get ya hehehe",
      tone: "free",
      matchups: [
        { champion: "Sylas", possessionValue: 10 },
        { champion: "Diana", possessionValue: 8 },
        { champion: "Jarvan IV", possessionValue: 8 },
        { champion: "Vi", possessionValue: 8 },
        { champion: "Ivern", possessionValue: 6 },
        { champion: "Nunu", possessionValue: 7 },
        { champion: "Ekko", possessionValue: 5 },
        { champion: "Master Yi", possessionValue: 4 },
      ],
    },
  ],
};
