import type { GuideJungleTierMatchupSectionConfig } from "@/lib/guides/matchupGuideTypes";

export const VIEGO_JUNGLE_TIER_MATCHUPS: GuideJungleTierMatchupSectionConfig = {
  title: "All matchups",
  tiers: [
    {
      id: "nightmare",
      label: "Nightmare",
      subtitle: "P-please don't hurt me >.<",
      tone: "nightmare",
      matchups: [
        { champion: "Lee Sin", possessionValue: 9 },
        { champion: "Talon", possessionValue: 5 },
        { champion: "Kha'Zix", possessionValue: 8 },
        { champion: "Rengar", possessionValue: 6 },
        { champion: "Qiyana", possessionValue: 6 },
      ],
    },
    {
      id: "difficult",
      label: "Difficult",
      subtitle: "It's winnable!!",
      tone: "difficult",
      matchups: [
        { champion: "Kindred", possessionValue: 4 },
        { champion: "Graves", possessionValue: 5 },
        { champion: "Jax", possessionValue: 7 },
        { champion: "Kayn", possessionValue: 5 },
        { champion: "Rammus", possessionValue: 8 },
        { champion: "Shaco", possessionValue: 5 },
        { champion: "Xin Zhao", possessionValue: 7 },
      ],
    },
    {
      id: "even",
      label: "Even",
      subtitle: "May the better kitten prevail!",
      tone: "even",
      matchups: [
        { champion: "Amumu", possessionValue: 5 },
        { champion: "Bel'Veth", possessionValue: 7 },
        { champion: "Elise", possessionValue: 4 },
        { champion: "Fiddlesticks", possessionValue: 5 },
        { champion: "Karthus", possessionValue: 5 },
        { champion: "Maokai", possessionValue: 5 },
        { champion: "Nasus", possessionValue: 5 },
        { champion: "Nocturne", possessionValue: 5 },
        { champion: "Poppy", possessionValue: 6 },
        { champion: "Sejuani", possessionValue: 6 },
        { champion: "Shyvana", possessionValue: 6 },
        { champion: "Wukong", possessionValue: 6 },
        {
          champion: "Zac",
          possessionValue: 8,
          isNew: true,
          explanation:
            "You can't punish his weak early, which sets him up for success for his insane midgame power.\n\nDon't get hit by his CC, don't forget about his crazy engage range and healing in fights. Surviving is his strength. Check the little wings next to his level to see if he has passive up.\n\nBut if he does mess up and you manage to burst him, his transformation is insane. You heal a lot, can instantly jump on your next target and guarantee your R. Even Zac passive works as Viego.",
        },
      ],
    },
    {
      id: "favorable",
      label: "Favored",
      subtitle: "Easy :3",
      tone: "favorable",
      matchups: [
        { champion: "Ambessa", possessionValue: 8 },
        { champion: "Briar", possessionValue: 8 },
        { champion: "Dr. Mundo", possessionValue: 5 },
        { champion: "Evelynn", possessionValue: 4 },
        { champion: "Gragas", possessionValue: 5 },
        { champion: "Gwen", possessionValue: 4 },
        { champion: "Hecarim", possessionValue: 7 },
        { champion: "Lillia", possessionValue: 5 },
        { champion: "Naafiri", possessionValue: 6, isNew: true },
        {
          champion: "Nidalee",
          possessionValue: 2,
          isNew: true,
          explanation:
            "She's super strong early. Almost always gets a lead in the beginning, thanks to her extremely high tempo and powerful neutral game. But struggles a lot with invading you.\n\nNida doesn't really have the damage to kill you in midgame and has no CC to lock you down.\n\nIn teamfights she's not a threat and if she ever facechecks into you, burst her. You outscale her and if she missteps on your spikes, she gets oneshot.\n\nShe is slippery though and will buy Zhonya's eventually. Don't get baited out of position for a low value reset.",
        },
        { champion: "Olaf", possessionValue: 5 },
        { champion: "Rek'Sai", possessionValue: 6 },
        { champion: "Skarner", possessionValue: 6 },
        { champion: "Udyr", possessionValue: 6 },
        { champion: "Volibear", possessionValue: 5 },
        {
          champion: "Warwick",
          possessionValue: 7,
          isNew: true,
          explanation:
            "Very easy to kill lategame. Warwick always has to go in with E and Q, so he exposes himself to a full combo. That combo oneshots him with LDR.\n\nBut his ultimate can be annoying in teamfights, you don't wanna get hit by that. Just be patient, wait for him to disrespect, burst him, snowball the fight.\n\nAnd watch out for his early invades. Especially in low elo, Warwicks like to lv 1,2 or 3 cheese invade you. Just ward your Raptors entrance and you should be good.",
        },
        { champion: "Zed", possessionValue: 8 },
      ],
    },
    {
      id: "free",
      label: "Free food",
      subtitle: "Awwwwwwwwwwh I'm gonna get ya hehehe",
      tone: "free",
      matchups: [
        { champion: "Sylas", possessionValue: 10 },
        { champion: "Diana", possessionValue: 8 },
        { champion: "Jarvan IV", possessionValue: 8 },
        { champion: "Vi", possessionValue: 8 },
        { champion: "Ivern", possessionValue: 6 },
        { champion: "Nunu", possessionValue: 7 },
        { champion: "Ekko", possessionValue: 8 },
        { champion: "Master Yi", possessionValue: 5 },
      ],
    },
  ],
};
