import type { GuideComboSectionConfig } from "@/lib/guides/comboGuideTypes";
import { guideComboVideo } from "@/lib/guides/guideComboVideos";

export const VIEGO_COMBO_SECTION: GuideComboSectionConfig = {
  heading: "Combo Guide",
  subtitle: "How and when to use each combo",
  combos: [
    {
      id: "q-extension",
      label: "Q extension",
      sequence: ["Wtap", "Q"],
      videoSrc: guideComboVideo("Q extension.webm"),
      ingameExampleVideoSrc: guideComboVideo("ingameQextension.webm"),
      explanation: "Cancel Q animation to extend the range. This way you can get resets, finish people off, do damage while chasing or running away and mark people for your R.",
    },
    {
      id: "q-extension-oneshot",
      label: "Q extension oneshot",
      sequence: ["Wtap", "Q", "R", "AA"],
      videoSrc: guideComboVideo("Q extension oneshot.webm"),
      ingameExampleVideoSrc: guideComboVideo("ingameQextensiononeshot.webm"),
      explanation: "Mark people with Q extension to increase R damage for a quick oneshot. Example below is without W.",
    },
    {
      id: "r-extension",
      label: "R extension",
      sequence: ["Wtap", "R"],
      videoSrc: guideComboVideo("R extension.webm"),
      ingameExampleVideoSrc: guideComboVideo("ingameRextension.webm"),
      explanation: "W > R extends the R range immediately. This only works with W, if you Lucian E > R your R will just have the normal range. Wait until the dash is completed before you R on other champions.",
    },
    {
      id: "r-extension-burst",
      label: "R extension burst",
      sequence: ["Wtap", "R", "Q", "AA"],
      videoSrc: guideComboVideo("R extension burst.webm"),
      ingameExampleVideoSrc: guideComboVideo("ingameRextensionburst.webm"),
      explanation: "Get in range quickly, Q first to apply the mark for the auto. Through with HOB your Q animation gets so fast after the first auto, it barely matters which order you do it in.",
    },
    {
      id: "w-tap-burst",
      label: "W tap burst",
      sequence: ["Wtap", "AA", "Q", "AA"],
      videoSrc: guideComboVideo("w tap burst.webm"),
      ingameExampleVideoSrc: guideComboVideo("ingameWtapburst.webm"),
      explanation: "Bread and butter. You walk up with E and do the basic burst combo. On 3 items this kills squishies.",
    },
    {
      id: "burst-combo",
      label: "Burst combo",
      sequence: ["Wcharge", "E", "AA", "Q", "R", "AA"],
      videoSrc: guideComboVideo("BurstCombo.webm"),
      explanation: "Use this to oneshot mobile squishies. Great against stuff like Ekko, Akali, Qiyana to kill them before they can dash away. Even works if they have mercs! You just need enough damage (usually with LDR + Cloak of Agility).",
    },
    {
      id: "extended-combo",
      label: "Extended burst combo",
      sequence: ["Wcharge", "E", "AA", "Q", "AA", "R", "AA"],
      videoSrc: guideComboVideo("extended combo.webm"),
      explanation: "Same as burst combo, but you use an extra auto before R. This will allow people to Flash out of your ult if they have tenacity or you lack attackspeed (low alacrity stacks without E active), but against champs like Talon/Akali you need to do the auto before your R. Otherwise they instantly go invis.",
    },
    {
      id: "ranged-stun-combo",
      label: "Ranged stun combo",
      sequence: ["Wcharge", "R", "Q", "AA"],
      videoSrc: guideComboVideo("RangedStun.webm"),
      ingameExampleVideoSrc: guideComboVideo("ingameRangedStun.webm"),
      explanation: "Usually you use this from fog over a wall. You can't get in range to auto, so the moment you know the stun connects you just ult and send it.",
    },
    {
      id: "hob-combo-in-wave",
      label: "HOB combo in wave",
      sequence: ["AA", "AA", "AA", "Wtap", "AA"],
      videoSrc: guideComboVideo("HOB auto combo.webm"),
      explanation: "Sometimes you can't hit W because you're getting body blocked, so you just use all HOB autos and then W auto reset for a fourth hit.",
    },
    {
      id: "squishy-burst",
      label: "Squishy burst",
      sequence: ["Wtap", "Q", "AA"],
      videoSrc: guideComboVideo("Squishy burst.webm"),
      ingameExampleVideoSrc: guideComboVideo("ingameSquishyBurst.webm"),
      explanation: "Sometimes this is all it takes...",
    },
    {
      id: "hidden-stun-initiator",
      label: "Hidden stun initiator",
      sequence: ["E", "Wcharge"],
      videoSrc: guideComboVideo("Hidden stun initiator.webm"),
      explanation: "Don't overuse this. If you hit it, the enemy dies, but often they will retreat immediately when they see your E and you're just wasting time/exposing yourself. I like to use this when I'm against someone that wants to fight me, or when I'm desperate for a pick on a mobile/tanky champion. Also if you're on a ward, you're about to get baited.",
    },
  ],
};
