ALTER TABLE "Session"
  ADD COLUMN IF NOT EXISTS "reminderSent" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "followupSent" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "couponCode" TEXT,
  ADD COLUMN IF NOT EXISTS "couponDiscount" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "PendingConfirmationDM" (
  "discordId" TEXT PRIMARY KEY,
  "message" TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "SessionAsset" (
  "id" TEXT PRIMARY KEY,
  "sessionId" TEXT NOT NULL,
  "assetId" TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "SessionAsset_sessionId_assetId_key"
  ON "SessionAsset"("sessionId","assetId");
