// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "@/app/_components/NavBar";
import NavGate from "@/app/_components/NavGate"; // client wrapper for conditional render

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0B0F1A] text-white`}
      >
        {/* ✅ NavBar appears globally, except hidden on /coaching/[preset] */}
        <NavGate>
          <NavBar />
        </NavGate>

        {children}
      </body>
    </html>
  );
}
